USE ONSIDE;

INSERT INTO Team (team_ID, league_ID, team_name, point, ranking, matches_played, matches_won, matches_lost, matches_draw) VALUES
(1, 1, 'Galatasaray', NULL, NULL, NULL, NULL, NULL, NULL),
(2, 1, 'Fenerbahçe', NULL, NULL, NULL, NULL, NULL, NULL),
(3, 1, 'Beşiktaş', NULL, NULL, NULL, NULL, NULL, NULL),
(4, 1, 'Trabzonspor', NULL, NULL, NULL, NULL, NULL, NULL),
(5, 1, 'Başakşehir', NULL, NULL, NULL, NULL, NULL, NULL),
(6, 1, 'Adana Demirspor', NULL, NULL, NULL, NULL, NULL, NULL),
(7, 1, 'Konyaspor', NULL, NULL, NULL, NULL, NULL, NULL),
(8, 1, 'Karagümrük', NULL, NULL, NULL, NULL, NULL, NULL),
(9, 1, 'Antalyaspor', NULL, NULL, NULL, NULL, NULL, NULL),
(10, 1, 'Gaziantep FK', NULL, NULL, NULL, NULL, NULL, NULL),
(11, 1, 'Alanyaspor', NULL, NULL, NULL, NULL, NULL, NULL),
(12, 1, 'İstanbulspor', NULL, NULL, NULL, NULL, NULL, NULL),
(13, 1, 'Kasımpaşa', NULL, NULL, NULL, NULL, NULL, NULL),
(14, 1, 'Sivasspor', NULL, NULL, NULL, NULL, NULL, NULL),
(15, 1, 'Kayserispor', NULL, NULL, NULL, NULL, NULL, NULL),
(16, 1, 'Ankaragücü', NULL, NULL, NULL, NULL, NULL, NULL),
(17, 1, 'Hatayspor', NULL, NULL, NULL, NULL, NULL, NULL),  
(18, 1, 'Giresunspor', NULL, NULL, NULL, NULL, NULL, NULL),
(19, 1, 'Samsunspor', NULL, NULL, NULL, NULL, NULL, NULL),
(20, 1, 'Pendikspor', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO Team (team_ID, league_ID, team_name, point, ranking, matches_played, matches_won, matches_lost, matches_draw) VALUES
(21, 2, 'Real Madrid', NULL, NULL, NULL, NULL, NULL, NULL),
(22, 2, 'Barcelona', NULL, NULL, NULL, NULL, NULL, NULL),
(23, 2, 'Atletico Madrid', NULL, NULL, NULL, NULL, NULL, NULL),
(24, 2, 'Valencia', NULL, NULL, NULL, NULL, NULL, NULL),
(25, 2, 'Sevilla', NULL, NULL, NULL, NULL, NULL, NULL),
(26, 2, 'Villarreal', NULL, NULL, NULL, NULL, NULL, NULL),
(27, 2, 'Real Sociedad', NULL, NULL, NULL, NULL, NULL, NULL),
(28, 2, 'Real Betis', NULL, NULL, NULL, NULL, NULL, NULL),
(29, 2, 'Athletic Bilbao', NULL, NULL, NULL, NULL, NULL, NULL),
(30, 2, 'Espanyol', NULL, NULL, NULL, NULL, NULL, NULL),
(31, 2, 'Celta Vigo', NULL, NULL, NULL, NULL, NULL, NULL),
(32, 2, 'Getafe', NULL, NULL, NULL, NULL, NULL, NULL),
(33, 2, 'Levante', NULL, NULL, NULL, NULL, NULL, NULL),
(34, 2, 'Real Valladolid', NULL, NULL, NULL, NULL, NULL, NULL),
(35, 2, 'Osasuna', NULL, NULL, NULL, NULL, NULL, NULL),
(36, 2, 'Granada', NULL, NULL, NULL, NULL, NULL, NULL),
(37, 2, 'Cadiz', NULL, NULL, NULL, NULL, NULL, NULL),
(38, 2, 'Elche', NULL, NULL, NULL, NULL, NULL, NULL),
(39, 2, 'Almeria', NULL, NULL, NULL, NULL, NULL, NULL),
(40, 2, 'Girona', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO Team (team_ID, league_ID, team_name, point, ranking, matches_played, matches_won, matches_lost, matches_draw) VALUES
(41, 3, 'Arsenal', NULL, NULL, NULL, NULL, NULL, NULL),
(42, 3, 'Aston Villa', NULL, NULL, NULL, NULL, NULL, NULL),
(43, 3, 'Bournemouth', NULL, NULL, NULL, NULL, NULL, NULL),
(44, 3, 'Brentford', NULL, NULL, NULL, NULL, NULL, NULL),
(45, 3, 'Brighton & Hove Albion', NULL, NULL, NULL, NULL, NULL, NULL),
(46, 3, 'Burnley', NULL, NULL, NULL, NULL, NULL, NULL),
(47, 3, 'Chelsea', NULL, NULL, NULL, NULL, NULL, NULL),
(48, 3, 'Crystal Palace', NULL, NULL, NULL, NULL, NULL, NULL),
(49, 3, 'Everton', NULL, NULL, NULL, NULL, NULL, NULL),
(50, 3, 'Fulham', NULL, NULL, NULL, NULL, NULL, NULL),
(51, 3, 'Liverpool', NULL, NULL, NULL, NULL, NULL, NULL),
(52, 3, 'Luton Town', NULL, NULL, NULL, NULL, NULL, NULL),
(53, 3, 'Manchester City', NULL, NULL, NULL, NULL, NULL, NULL),
(54, 3, 'Manchester United', NULL, NULL, NULL, NULL, NULL, NULL),
(55, 3, 'Newcastle United', NULL, NULL, NULL, NULL, NULL, NULL),
(56, 3, 'Nottingham Forest', NULL, NULL, NULL, NULL, NULL, NULL),
(57, 3, 'Sheffield United', NULL, NULL, NULL, NULL, NULL, NULL),
(58, 3, 'Tottenham Hotspur', NULL, NULL, NULL, NULL, NULL, NULL),
(59, 3, 'West Ham United', NULL, NULL, NULL, NULL, NULL, NULL),
(60, 3, 'Wolverhampton Wanderers', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO Team (team_ID, league_ID, team_name, point, ranking, matches_played, matches_won, matches_lost, matches_draw) VALUES
(61, 4, 'Paris Saint-Germain', NULL, NULL, NULL, NULL, NULL, NULL),
(62, 4, 'Lens', NULL, NULL, NULL, NULL, NULL, NULL),
(63, 4, 'Olympique de Marseille', NULL, NULL, NULL, NULL, NULL, NULL),
(64, 4, 'Rennes', NULL, NULL, NULL, NULL, NULL, NULL),
(65, 4, 'Lille', NULL, NULL, NULL, NULL, NULL, NULL),
(66, 4, 'Monaco', NULL, NULL, NULL, NULL, NULL, NULL),
(67, 4, 'Olympique Lyonnais', NULL, NULL, NULL, NULL, NULL, NULL),
(68, 4, 'Nice', NULL, NULL, NULL, NULL, NULL, NULL),
(69, 4, 'Reims', NULL, NULL, NULL, NULL, NULL, NULL),
(70, 4, 'Montpellier', NULL, NULL, NULL, NULL, NULL, NULL),
(71, 4, 'Strasbourg', NULL, NULL, NULL, NULL, NULL, NULL),
(72, 4, 'Clermont Foot', NULL, NULL, NULL, NULL, NULL, NULL),
(73, 4, 'Brest', NULL, NULL, NULL, NULL, NULL, NULL),
(74, 4, 'Toulouse', NULL, NULL, NULL, NULL, NULL, NULL),
(75, 4, 'Nantes', NULL, NULL, NULL, NULL, NULL, NULL),
(76, 4, 'Angers', NULL, NULL, NULL, NULL, NULL, NULL),
(77, 4, 'Metz', NULL, NULL, NULL, NULL, NULL, NULL),
(78, 4, 'Eiffel FC', NULL, NULL, NULL, NULL, NULL, NULL),
(79, 4, 'Le Havre', NULL, NULL, NULL, NULL, NULL, NULL),
(80, 4, 'Lorient', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO Team (team_ID, league_ID, team_name, point, ranking, matches_played, matches_won, matches_lost, matches_draw) VALUES

(81, 5, 'Borussia Dortmund', NULL, NULL, NULL, NULL, NULL, NULL),
(82, 5, 'RB Leipzig', NULL, NULL, NULL, NULL, NULL, NULL),
(83, 5, 'Bayer Leverkusen', NULL, NULL, NULL, NULL, NULL, NULL),
(84, 5, 'VfL Wolfsburg', NULL, NULL, NULL, NULL, NULL, NULL),
(85, 5, 'Eintracht Frankfurt', NULL, NULL, NULL, NULL, NULL, NULL),
(86, 5, 'Borussia Mönchengladbach', NULL, NULL, NULL, NULL, NULL, NULL),
(87, 5, 'TSG 1899 Hoffenheim', NULL, NULL, NULL, NULL, NULL, NULL),
(88, 5, 'SC Freiburg', NULL, NULL, NULL, NULL, NULL, NULL),
(89, 5, 'FC Augsburg', NULL, NULL, NULL, NULL, NULL, NULL),
(90, 5, '1. FSV Mainz 05', NULL, NULL, NULL, NULL, NULL, NULL),
(91, 5, 'VfB Stuttgart', NULL, NULL, NULL, NULL, NULL, NULL),
(92, 5, 'Hertha BSC', NULL, NULL, NULL, NULL, NULL, NULL),
(93, 5, '1. FC Köln', NULL, NULL, NULL, NULL, NULL, NULL),
(94, 5, 'SV Werder Bremen', NULL, NULL, NULL, NULL, NULL, NULL),
(95, 5, 'VFC Bochum', NULL, NULL, NULL, NULL, NULL, NULL),
(96, 5, 'FC Heidenheim', NULL, NULL, NULL, NULL, NULL, NULL), 
(97, 5, 'SV Darmstadt 98', NULL, NULL, NULL, NULL, NULL, NULL),
(98, 5, 'Bayern Munich', NULL, NULL, NULL, NULL, NULL, NULL),
(99, 5, 'Ulm FC', NULL, NULL, NULL, NULL, NULL, NULL),
(100, 5, 'TurkGucu FC', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO Team (team_ID, league_ID, team_name, point, ranking, matches_played, matches_won, matches_lost, matches_draw) VALUES
(101, 6, 'Anadolu Efes', NULL, NULL, NULL, NULL, NULL, NULL),
(102, 6, 'Fenerbahçe Beko', NULL, NULL, NULL, NULL, NULL, NULL),
(103, 6, 'Galatasaray Nef', NULL, NULL, NULL, NULL, NULL, NULL),
(104, 6, 'Beşiktaş Icrypex', NULL, NULL, NULL, NULL, NULL, NULL),
(105, 6, 'Darüşşafaka', NULL, NULL, NULL, NULL, NULL, NULL),
(106, 6, 'Türk Telekom', NULL, NULL, NULL, NULL, NULL, NULL),
(107, 6, 'Tofaş', NULL, NULL, NULL, NULL, NULL, NULL),
(108, 6, 'Pınar Karşıyaka', NULL, NULL, NULL, NULL, NULL, NULL),
(109, 6, 'Gaziantep Basketbol', NULL, NULL, NULL, NULL, NULL, NULL),
(110, 6, 'Bahçeşehir Koleji', NULL, NULL, NULL, NULL, NULL, NULL),
(111, 6, 'Bursaspor', NULL, NULL, NULL, NULL, NULL, NULL),
(112, 6, 'Afyon Belediyespor', NULL, NULL, NULL, NULL, NULL, NULL),
(113, 6, 'Petkim Spor', NULL, NULL, NULL, NULL, NULL, NULL),
(114, 6, ' Büyükçekmece Basketbol', NULL, NULL, NULL, NULL, NULL, NULL),
(115, 6, 'Manisa Büyükşehir Belediyespor', NULL, NULL, NULL, NULL, NULL, NULL),
(116, 6, 'Samsunspor', NULL, NULL, NULL, NULL, NULL, NULL),
(117, 6, 'Merkezefendi Belediyesi Denizli Basket', NULL, NULL, NULL, NULL, NULL, NULL),
(118, 6, 'Onvo Büyükçekmece', NULL, NULL, NULL, NULL, NULL, NULL),
(119, 6, 'Konyaspor', NULL, NULL, NULL, NULL, NULL, NULL),
(120, 6, 'Antalya Güneşi', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO Team (team_ID, league_ID, team_name, point, ranking, matches_played, matches_won, matches_lost, matches_draw) VALUES
(121, 7, 'Madritistas', NULL, NULL, NULL, NULL, NULL, NULL),
(122, 7, 'Catalonia', NULL, NULL, NULL, NULL, NULL, NULL),
(123, 7, 'Efes Pilsen', NULL, NULL, NULL, NULL, NULL, NULL),
(124, 7, 'Ülker Beko', NULL, NULL, NULL, NULL, NULL, NULL),
(125, 7, 'Olympiacos', NULL, NULL, NULL, NULL, NULL, NULL),
(126, 7, 'Panathinaikos', NULL, NULL, NULL, NULL, NULL, NULL),
(127, 7, 'Maccabi Tel Aviv', NULL, NULL, NULL, NULL, NULL, NULL),
(128, 7, 'CSKA Moscow', NULL, NULL, NULL, NULL, NULL, NULL),
(129, 7, 'Partizan Belgrade', NULL, NULL, NULL, NULL, NULL, NULL),
(130, 7, 'Crvena zvezda mts Belgrade', NULL, NULL, NULL, NULL, NULL, NULL),
(131, 7, 'Žalgiris', NULL, NULL, NULL, NULL, NULL, NULL),
(132, 7, 'ALBA Berlin', NULL, NULL, NULL, NULL, NULL, NULL),
(133, 7, 'ASVEL', NULL, NULL, NULL, NULL, NULL, NULL),
(134, 7, 'Bayern Munich', NULL, NULL, NULL, NULL, NULL, NULL),
(135, 7, 'Valverde Basket', NULL, NULL, NULL, NULL, NULL, NULL),
(136, 7, 'Virtus Segafredo Bologna', NULL, NULL, NULL, NULL, NULL, NULL),
(137, 7, 'AS Monaco', NULL, NULL, NULL, NULL, NULL, NULL),
(138, 7, 'Arel Uni', NULL, NULL, NULL, NULL, NULL, NULL),
(139, 7, 'Bayes Basketball', NULL, NULL, NULL, NULL, NULL, NULL),
(140, 7, 'Daltons', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO Team (team_ID, league_ID, team_name, point, ranking, matches_played, matches_won, matches_lost, matches_draw) VALUES
(141, 8, 'Atlanta Hawks', NULL, NULL, NULL, NULL, NULL, NULL),
(142, 8, 'Boston Celtics', NULL, NULL, NULL, NULL, NULL, NULL),
(143, 8, 'Brooklyn Nets', NULL, NULL, NULL, NULL, NULL, NULL),
(144, 8, 'Charlotte Hornets', NULL, NULL, NULL, NULL, NULL, NULL),
(145, 8, 'Chicago Bulls', NULL, NULL, NULL, NULL, NULL, NULL),
(146, 8, 'Cleveland Cavaliers', NULL, NULL, NULL, NULL, NULL, NULL),
(147, 8, 'Dallas Mavericks', NULL, NULL, NULL, NULL, NULL, NULL),
(148, 8, 'Denver Nuggets', NULL, NULL, NULL, NULL, NULL, NULL),
(149, 8, 'Detroit Pistons', NULL, NULL, NULL, NULL, NULL, NULL),
(150, 8, 'Golden State Warriors', NULL, NULL, NULL, NULL, NULL, NULL),
(151, 8, 'Houston Rockets', NULL, NULL, NULL, NULL, NULL, NULL),
(152, 8, 'Indiana Pacers', NULL, NULL, NULL, NULL, NULL, NULL),
(153, 8, 'Los Angeles Clippers', NULL, NULL, NULL, NULL, NULL, NULL),
(154, 8, 'Los Angeles Lakers', NULL, NULL, NULL, NULL, NULL, NULL),
(155, 8, 'Memphis Grizzlies', NULL, NULL, NULL, NULL, NULL, NULL),
(156, 8, 'Miami Heat', NULL, NULL, NULL, NULL, NULL, NULL),
(157, 8, 'Milwaukee Bucks', NULL, NULL, NULL, NULL, NULL, NULL),
(158, 8, 'Minnesota Timberwolves', NULL, NULL, NULL, NULL, NULL, NULL),
(159, 8, 'New Orleans Pelicans', NULL, NULL, NULL, NULL, NULL, NULL),
(160, 8, 'New York Knicks', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO Team (team_ID, league_ID, team_name, point, ranking, matches_played, matches_won, matches_lost, matches_draw) VALUES
(161, 9, 'Real Madrid', NULL, NULL, NULL, NULL, NULL, NULL),
(162, 9, 'Barcelona', NULL, NULL, NULL, NULL, NULL, NULL),
(163, 9, 'Baskonia', NULL, NULL, NULL, NULL, NULL, NULL),
(164, 9, 'Valencia Basket', NULL, NULL, NULL, NULL, NULL, NULL),
(165, 9, 'Joventut Badalona', NULL, NULL, NULL, NULL, NULL, NULL),
(166, 9, 'Unicaja', NULL, NULL, NULL, NULL, NULL, NULL),
(167, 9, 'Gran Canaria', NULL, NULL, NULL, NULL, NULL, NULL),
(168, 9, 'Tenerife', NULL, NULL, NULL, NULL, NULL, NULL),
(169, 9, 'Bilbao Basket', NULL, NULL, NULL, NULL, NULL, NULL),
(170, 9, 'Obradoiro', NULL, NULL, NULL, NULL, NULL, NULL),
(171, 9, 'Manresa', NULL, NULL, NULL, NULL, NULL, NULL),
(172, 9, 'Girona', NULL, NULL, NULL, NULL, NULL, NULL),
(173, 9, 'Estudiantes', NULL, NULL, NULL, NULL, NULL, NULL),
(174, 9, 'Fuenlabrada', NULL, NULL, NULL, NULL, NULL, NULL),
(175, 9, 'Zaragoza', NULL, NULL, NULL, NULL, NULL, NULL),
(176, 9, 'Breogan', NULL, NULL, NULL, NULL, NULL, NULL),
(177, 9, 'Andorra', NULL, NULL, NULL, NULL, NULL, NULL),
(178, 9, 'Murcia', NULL, NULL, NULL, NULL, NULL, NULL),
(179, 9, 'Kautec', NULL, NULL, NULL, NULL, NULL, NULL),
(180, 9, 'Latifi', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO Team (team_ID, league_ID, team_name, point, ranking, matches_played, matches_won, matches_lost, matches_draw) VALUES
(181, 10, 'Adana Şakirpaşa Spor', NULL, NULL, NULL, NULL, NULL, NULL),
(182, 10, 'Seyhan Gençlik', NULL, NULL, NULL, NULL, NULL, NULL),
(183, 10, 'Yüreğir Basketbol', NULL, NULL, NULL, NULL, NULL, NULL),
(184, 10, 'Çukurova Basket', NULL, NULL, NULL, NULL, NULL, NULL),
(185, 10, 'Sarıçam Sportif', NULL, NULL, NULL, NULL, NULL, NULL),
(186, 10, 'Ceyhan Gençlik', NULL, NULL, NULL, NULL, NULL, NULL),
(187, 10, 'Karaisalı Basketbol Kulübü', NULL, NULL, NULL, NULL, NULL, NULL),
(188, 10, 'Pozantı Spor', NULL, NULL, NULL, NULL, NULL, NULL),
(189, 10, 'Tufanbeyli Basketbol', NULL, NULL, NULL, NULL, NULL, NULL),
(190, 10, 'Feke Gençlik Spor', NULL, NULL, NULL, NULL, NULL, NULL),
(191, 10, 'İmamoğlu Basketbol', NULL, NULL, NULL, NULL, NULL, NULL),
(192, 10, 'Kebap FC', NULL, NULL, NULL, NULL, NULL, NULL), 
(193, 10, 'Şalgamspor', NULL, NULL, NULL, NULL, NULL, NULL),  
(194, 10, 'Bici Bici Basketbol', NULL, NULL, NULL, NULL, NULL, NULL), 
(195, 10, 'Çİfteminare', NULL, NULL, NULL, NULL, NULL, NULL),
(196, 10, 'Şırdan', NULL, NULL, NULL, NULL, NULL, NULL),
(197, 10, 'Taşköprü Basket', NULL, NULL, NULL, NULL, NULL, NULL),
(198, 10, 'Seyhanlılar', NULL, NULL, NULL, NULL, NULL, NULL),
(199, 10, 'Çukurovalılar', NULL, NULL, NULL, NULL, NULL, NULL),
(200, 10, 'Adana Liderspor', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO Team (team_ID, league_ID, team_name, point, ranking, matches_played, matches_won, matches_lost, matches_draw) VALUES
(201, 11, 'Eczacıbaşı Dynavit', NULL, NULL, NULL, NULL, NULL, NULL),
(202, 11, 'VakıfBank Spor Kulübü', NULL, NULL, NULL, NULL, NULL, NULL),
(203, 11, 'Fenerbahçe Opet', NULL, NULL, NULL, NULL, NULL, NULL),
(204, 11, 'Galatasaray HDI Sigorta', NULL, NULL, NULL, NULL, NULL, NULL),
(205, 11, 'THY', NULL, NULL, NULL, NULL, NULL, NULL),
(206, 11, 'Aydın Büyükşehir Belediyespor', NULL, NULL, NULL, NULL, NULL, NULL),
(207, 11, 'Nilüfer Belediyespor', NULL, NULL, NULL, NULL, NULL, NULL),
(208, 11, 'PTT', NULL, NULL, NULL, NULL, NULL, NULL),
(209, 11, 'Kuzeyboru', NULL, NULL, NULL, NULL, NULL, NULL),
(210, 11, 'Çukurova Belediyespor', NULL, NULL, NULL, NULL, NULL, NULL),
(211, 11, 'Sarıyer Belediyespor', NULL, NULL, NULL, NULL, NULL, NULL),
(212, 11, 'İlbank', NULL, NULL, NULL, NULL, NULL, NULL),
(213, 11, 'Mert Grup Sigorta', NULL, NULL, NULL, NULL, NULL, NULL),
(214, 11, 'Ankara Karayolları', NULL, NULL, NULL, NULL, NULL, NULL),  
(215, 11, 'Bolu Belediyespor', NULL, NULL, NULL, NULL, NULL, NULL),
(216, 11, 'Eva Voleybol', NULL, NULL, NULL, NULL, NULL, NULL), 
(217, 11, 'File Spor', NULL, NULL, NULL, NULL, NULL, NULL), 
(218, 11, 'Smaçörler', NULL, NULL, NULL, NULL, NULL, NULL), 
(219, 11, 'Blok Kraliçeleri', NULL, NULL, NULL, NULL, NULL, NULL), 
(220, 11, 'Voleybol Güneşi', NULL, NULL, NULL, NULL, NULL, NULL); 

INSERT INTO Team (team_ID, league_ID, team_name, point, ranking, matches_played, matches_won, matches_lost, matches_draw) VALUES
(221, 12, 'Powerpuff Girls', NULL, NULL, NULL, NULL, NULL, NULL),
(222, 12, 'Metek Girls', NULL, NULL, NULL, NULL, NULL, NULL),
(223, 12, 'Imoco Volley Conegliano', NULL, NULL, NULL, NULL, NULL, NULL),
(224, 12, 'Igor Gorgonzola Novara', NULL, NULL, NULL, NULL, NULL, NULL),
(225, 12, 'A. Carraro Imoco Conegliano', NULL, NULL, NULL, NULL, NULL, NULL),
(226, 12, 'Savino Del Bene Scandicci', NULL, NULL, NULL, NULL, NULL, NULL),
(227, 12, 'Developres Rzeszów', NULL, NULL, NULL, NULL, NULL, NULL),
(228, 12, 'Lokomotiv Kaliningrad', NULL, NULL, NULL, NULL, NULL, NULL),  
(229, 12, 'Paris Volleys', NULL, NULL, NULL, NULL, NULL, NULL),
(230, 12, 'Berlin Spikers', NULL, NULL, NULL, NULL, NULL, NULL),
(231, 12, 'Roma Smashers', NULL, NULL, NULL, NULL, NULL, NULL),
(232, 12, 'Madrid Aces', NULL, NULL, NULL, NULL, NULL, NULL),
(233, 12, 'London Lions', NULL, NULL, NULL, NULL, NULL, NULL),
(234, 12, 'Vienna Vikings', NULL, NULL, NULL, NULL, NULL, NULL),
(235, 12, 'Prague Panthers', NULL, NULL, NULL, NULL, NULL, NULL),
(236, 12, 'Budapest Hornets', NULL, NULL, NULL, NULL, NULL, NULL),
(237, 12, 'Warsaw Eagles', NULL, NULL, NULL, NULL, NULL, NULL),
(238, 12, 'Bucharest Bears', NULL, NULL, NULL, NULL, NULL, NULL),
(239, 12, 'Sofia Sharks', NULL, NULL, NULL, NULL, NULL, NULL),
(240, 12, 'Zagreb Wolves', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO Team (team_ID, league_ID, team_name, point, ranking, matches_played, matches_won, matches_lost, matches_draw) VALUES
(241, 13, 'Tianjin Bohai Bank', NULL, NULL, NULL, NULL, NULL, NULL),
(242, 13, 'Shanghai Bright Ubest', NULL, NULL, NULL, NULL, NULL, NULL),
(243, 13, 'Jiangsu Zenith Steel', NULL, NULL, NULL, NULL, NULL, NULL),
(244, 13, 'Beijing BAIC Motor', NULL, NULL, NULL, NULL, NULL, NULL),
(245, 13, 'Liaoning Huajun', NULL, NULL, NULL, NULL, NULL, NULL),
(246, 13, 'Zhejiang Jiaxing Xitang Ancient Town', NULL, NULL, NULL, NULL, NULL, NULL),
(247, 13, 'Shandong Rizhao Steel', NULL, NULL, NULL, NULL, NULL, NULL),
(248, 13, 'Henan', NULL, NULL, NULL, NULL, NULL, NULL),
(249, 13, 'Fujian', NULL, NULL, NULL, NULL, NULL, NULL),  
(250, 13, 'Guangdong Evergrande', NULL, NULL, NULL, NULL, NULL, NULL),
(251, 13, 'Sichuan Volleyball', NULL, NULL, NULL, NULL, NULL, NULL),
(252, 13, 'Hubei Wuhan', NULL, NULL, NULL, NULL, NULL, NULL),
(253, 13, 'Hebei Great Wall', NULL, NULL, NULL, NULL, NULL, NULL),
(254, 13, 'Shanxi Coal', NULL, NULL, NULL, NULL, NULL, NULL),
(255, 13, 'Anhui Energy', NULL, NULL, NULL, NULL, NULL, NULL),
(256, 13, 'Hunan Xiangjiang', NULL, NULL, NULL, NULL, NULL, NULL),
(257, 13, 'Jilin Northeast Tigers', NULL, NULL, NULL, NULL, NULL, NULL),
(258, 13, 'Heilongjiang Aurora', NULL, NULL, NULL, NULL, NULL, NULL),
(259, 13, 'Inner Mongolia Riders', NULL, NULL, NULL, NULL, NULL, NULL),
(260, 13, 'Xinjiang Snow Leopards', NULL, NULL, NULL, NULL, NULL, NULL);


INSERT INTO Team (team_ID, league_ID, team_name, point, ranking, matches_played, matches_won, matches_lost, matches_draw) VALUES

(261, 14, 'Praia Clube', NULL, NULL, NULL, NULL, NULL, NULL),
(262, 14, 'Minas', NULL, NULL, NULL, NULL, NULL, NULL),
(263, 14, 'Sesi Vôlei Bauru', NULL, NULL, NULL, NULL, NULL, NULL),
(264, 14, 'Osasco São Cristóvão Saúde', NULL, NULL, NULL, NULL, NULL, NULL),
(265, 14, 'Fluminense', NULL, NULL, NULL, NULL, NULL, NULL),
(266, 14, 'Pinheiros', NULL, NULL, NULL, NULL, NULL, NULL),
(267, 14, 'Barueri', NULL, NULL, NULL, NULL, NULL, NULL),
(268, 14, 'Brasília Vôlei', NULL, NULL, NULL, NULL, NULL, NULL),
(269, 14, 'Rio de Janeiro Vôlei Clube', NULL, NULL, NULL, NULL, NULL, NULL),
(270, 14, 'São Paulo Vôlei', NULL, NULL, NULL, NULL, NULL, NULL),
(271, 14, 'Belo Horizonte Stars', NULL, NULL, NULL, NULL, NULL, NULL),
(272, 14, 'Curitiba Smashers', NULL, NULL, NULL, NULL, NULL, NULL),
(273, 14, 'Porto Alegre Vipers', NULL, NULL, NULL, NULL, NULL, NULL),
(274, 14, 'Recife Aces', NULL, NULL, NULL, NULL, NULL, NULL),
(275, 14, 'Salvador Sharks', NULL, NULL, NULL, NULL, NULL, NULL),
(276, 14, 'Fortaleza Titans', NULL, NULL, NULL, NULL, NULL, NULL),
(277, 14, 'Manaus Amazons', NULL, NULL, NULL, NULL, NULL, NULL),
(278, 14, 'Goiânia Miners', NULL, NULL, NULL, NULL, NULL, NULL),
(279, 14, 'Belém Eagles', NULL, NULL, NULL, NULL, NULL, NULL),
(280, 14, 'Campinas Stars', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO Team (team_ID, league_ID, team_name, point, ranking, matches_played, matches_won, matches_lost, matches_draw) VALUES
(281, 15, 'Lefkoşa Voleybol Kulübü', NULL, NULL, NULL, NULL, NULL, NULL),
(282, 15, 'Gazimağusa Spor Kulübü', NULL, NULL, NULL, NULL, NULL, NULL),
(283, 15, 'Girne Voleybol', NULL, NULL, NULL, NULL, NULL, NULL),
(284, 15, 'Güzelyurt Spor', NULL, NULL, NULL, NULL, NULL, NULL),
(285, 15, 'İskele Voleybol Takımı', NULL, NULL, NULL, NULL, NULL, NULL),
(286, 15, 'Lefke Smaçörleri', NULL, NULL, NULL, NULL, NULL, NULL),
(287, 15, 'Magosa File', NULL, NULL, NULL, NULL, NULL, NULL),
(288, 15, 'Girne Kartalları', NULL, NULL, NULL, NULL, NULL, NULL),
(289, 15, 'Güzelyurt Aslanları', NULL, NULL, NULL, NULL, NULL, NULL),
(290, 15, 'İskele Yıldızları', NULL, NULL, NULL, NULL, NULL, NULL),
(291, 15, 'Lefkoşa Şimşekleri', NULL, NULL, NULL, NULL, NULL, NULL),
(292, 15, 'Gazimağusa Kaplanları', NULL, NULL, NULL, NULL, NULL, NULL),
(293, 15, 'Girne Yunusları', NULL, NULL, NULL, NULL, NULL, NULL),
(294, 15, 'Güzelyurt Kartalları', NULL, NULL, NULL, NULL, NULL, NULL),
(295, 15, 'İskele Panterleri', NULL, NULL, NULL, NULL, NULL, NULL),
(296, 15, 'Mağusa Voleybol', NULL, NULL, NULL, NULL, NULL, NULL),
(297, 15, 'Girne Spor Kulübü', NULL, NULL, NULL, NULL, NULL, NULL),
(298, 15, 'Güzelyurt Voleybol', NULL, NULL, NULL, NULL, NULL, NULL),
(299, 15, 'İskele Gençlik', NULL, NULL, NULL, NULL, NULL, NULL),
(300, 15, 'KKTC Voleybol', NULL, NULL, NULL, NULL, NULL, NULL);